name: Deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: yarn install
            - run: yarn run test
              env:
                  CI: true
            - run: yarn run build
              env:
                  NODE_ENV: production
                  REFERRALS_ORIGIN: https://mapgrid.org
                  REFERRALS_ENDPOINT: https://signup.mapgrid.workers.dev/
                  ANALYTICS_ENDPOINT: https://analytics.mapgrid.workers.dev/
            - run: yarn run deploy
              env:
                  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
                  CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
                  NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
